### ISSUE TITLE
Package babel Error: Unknown option `ngerman'. Either you misspelled itd. \ProcessOptions*

### ISSUE THREAD

**Issue by zichuan-liu** [latextemplates/ieee-enhanced#5]
???
please tell me how to do, thx

**Comment by 775269512** [comment]
oh,i get it

**Comment by zichuan-liu** [comment]
> ???
> please tell me how to do, thx

oh, i get it

**Comment by koppor** [comment]
This again motivates the [LaTeX Template Generator](https://github.com/latextemplates/generator-latex-template). Any support is highly welcome.

I fixed in the latest release. see https://github.com/latextemplates/IEEE/releases/tag/v1.5.0.

Fix code: https://github.com/latextemplates/IEEE/commit/07a33e0e6455e12a8a7f04e71f295ccea06aae6a
